### PR TITLE
#478,437/starred-menu-animation

### LINKED ISSUE #437: UI of the Starred Accounts
There is no margin at the bottom of the `Starred Accounts` which make it look a bit weird. I also would suggest we keep the title not moving with the whole region so that users know they are scrolling the starred accounts.

### LINKED ISSUE #478: Enhance starred accounts message on the left menu
I think we should show something like this on Ledger Live instead of the current message.

image

### PR DESCRIPTION
**Pull request by rachelhox**
closes #437 #478

### CODE REVIEW

**Comment by rachelhox** [comment]
Unit Test:
https://github.com/felippenardi/lottie-react-web/issues/21#issuecomment-611252768

**Comment by calvinkei** [comment]
we might need a lottie file for light theme @nicoletting

**Comment by nicoletting** [comment]
Uploaded, check please 🙇🏻‍♀️
@calvinkei 
https://drive.google.com/drive/u/1/folders/13pP_EZv_Rj2LXlLBryf1AqNwbtq07Gka

**Comment by calvinkei** [comment]
@rachelhox please add design for light theme. thanks!

**Pull request merged**
